### ISSUE TITLE
Request for Translated data

### ISSUE THREAD

**Issue by nikitacs16** [abteen/americasnli#1]
As is the practice with the XNLI dataset, could you please also release the machine translations of the dataset as seen in Table 3 of the paper

Thank you

**Comment by abteen** [comment]
Hi! Thanks for the request -- the data used for the project can be found here: https://drive.google.com/file/d/1gIVpV1E2Bp__5E3bJJ1uh1M5ClLUKPIs/view?usp=sharing

This includes the translated labeled data, and translated unlabeled data used for the experiments in the results. Please let me know if you have any trouble accessing the file!

Thanks,

Abteen
