### ISSUE TITLE
Trouble accessing data

### ISSUE THREAD

**Issue by jjdelvalle** [abteen/americasnli#2]
Data is no longer accessible under the link that was shared in a previous issue (#1) and the README file, i.e. https://drive.google.com/file/d/1gIVpV1E2Bp__5E3bJJ1uh1M5ClLUKPIs/view?usp=sharing

Is there an updated link or maybe another way to access the data?

Thank you for all the hard work!

**Comment by abteen** [comment]
Thanks for pointing this out! I've posted an updated link in the readme.

**Comment by jjdelvalle** [comment]
Thank you for the quick response! The new link works.
